export const demoHtml = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Distributor native demo</title><link rel="stylesheet" href="/demo/style.css"><script defer src="/demo/control.js"></script></head>
<body><main><p class="badge">FICTIONAL DEMO · ACTUAL DISTRIBUTOR APPLICATION</p><h1>Your private Distributor workspace</h1>
<p>The complete native interface runs against a temporary database for this browser. Use fictional details only. This is a local demonstration; selecting Canada or United States changes business rules and currency, not the computer's physical location.</p>
<p>Payments are simulated: choose successful payments, unpaid checkouts, expired checkouts, pending refunds or failed refunds below. The demo worker processes prepared operations (usually within a second). Pending refunds stay pending on refresh. Unpaid checkouts can be closed with the native finance action. Reset to explore a different scenario; no hosted card-entry form is simulated. No card details or real money are involved. Maple Workshop starts with fictional payment, accounting and carrier permissions that you can withdraw. Carrier booking creates clearly marked demo labels; Canada Post also uses the native grouped manifest step. Complete warehouse handover separately to ship and invoice. QuickBooks invoice, payment, credit, refund and balance workflows use a separate fictional accounting ledger. Use fictional mapping references such as demo-customer, demo-item, demo-tax and demo-bank. No Intuit account or OAuth connection is created. Email transport remains disabled.</p>
<section id="start"><form id="create"><label>Fictional company name<input name="companyName" required maxlength="80" value="Northstar Demo Distribution"></label><label>Business region<select name="region"><option value="CA">Canada · CAD</option><option value="US">United States · USD</option></select></label><label>Payment scenario<select name="paymentScenario"><option value="success">Successful checkout and refund</option><option value="unpaid">Unpaid checkout · close without payment</option><option value="expired">Expired checkout · review replacement</option><option value="pending-refund">Successful checkout · refund stays pending</option><option value="failed-refund">Successful checkout · refund fails</option></select></label><button>Create my demo</button></form></section>
<section id="workspace" hidden><h2 id="company"></h2><p id="lifetime"></p><p><a href="/">Return to the application</a></p><label>Explore as<select id="role"></select></label><button id="switch">Enter application as selected role</button><details><summary>Private demo sign-in details</summary><p>These generated credentials work only in this browser's current temporary workspace. Role switching uses the native login and respects any password or MFA changes you make.</p><pre id="credentials"></pre><a href="/">Open native sign-in</a></details><button id="reset" class="secondary">Erase this demo and start again</button></section>
<p id="message" role="status" aria-live="polite"></p></main></body></html>`;
export const demoCss = `:root{font:16px/1.55 system-ui;color:#eaf0f8;background:#111a2b}body{margin:0;padding:36px 18px}main{max-width:780px;margin:auto}h1{font-size:2.2rem;line-height:1.15}.badge{color:#81daca;font-size:.8rem;letter-spacing:.06em}section{background:#1c2940;padding:24px;border-radius:14px;margin:24px 0}label{display:block;margin:16px 0}input,select,button{font:inherit;padding:12px;border-radius:6px;border:1px solid #64758f;box-sizing:border-box}input,select{display:block;width:100%;margin-top:6px;color:#edf4ff;background:#111a2b}button{background:#80ddc7;color:#102623;cursor:pointer;margin:10px 10px 10px 0}.secondary{background:transparent;color:#fff}a{color:#a8dbff}pre{white-space:pre-wrap;overflow-wrap:anywhere}button:disabled{opacity:.5}#message{min-height:2em;color:#ffd38c}[hidden]{display:none!important}`;
export const demoScript = `"use strict";
let state;
const byId=id=>document.getElementById(id);
async function request(path,body){const response=await fetch('/demo/api/'+path,{method:body?'POST':'GET',headers:body?{'content-type':'application/json','x-demo-csrf':state.csrf}:{},body:body?JSON.stringify(body):undefined,credentials:'same-origin'});const value=await response.json();if(!response.ok)throw new Error(value.message||'Demo request failed.');return value;}
function clearDrafts(){for(const storage of [localStorage,sessionStorage]){for(const key of Object.keys(storage)){if(key.startsWith('distributor'))storage.removeItem(key);}}}
async function refresh(){state=await request('status');byId('start').hidden=state.active;byId('workspace').hidden=!state.active;if(state.active){byId('company').textContent=state.companyName+' · '+state.region+' · payment scenario: '+state.paymentScenario;byId('lifetime').textContent='Workspace expires after '+Math.round(state.idleTtlMs/60000)+' minutes without requests or '+Math.round(state.maxLifetimeMs/3600000)+' hours total. Reset permanently erases its fictional records.';byId('role').replaceChildren(...state.accounts.map(account=>{const option=document.createElement('option');option.value=account.role;option.textContent=account.role+' — '+account.email;return option;}));byId('credentials').textContent=state.accounts.map(a=>a.role+': '+a.email+' / '+a.password).join('\\n');}}
async function action(callback){byId('message').textContent='Working…';for(const button of document.querySelectorAll('button'))button.disabled=true;try{await callback();byId('message').textContent='';}catch(error){byId('message').textContent=error.message;}finally{for(const button of document.querySelectorAll('button'))button.disabled=false;}}
byId('create').addEventListener('submit',event=>{event.preventDefault();void action(async()=>{const data=new FormData(event.target);await request('start',{companyName:data.get('companyName'),region:data.get('region'),paymentScenario:data.get('paymentScenario')});clearDrafts();await refresh();});});
byId('switch').addEventListener('click',()=>void action(async()=>{await request('role',{role:byId('role').value});clearDrafts();location.assign('/');}));
byId('reset').addEventListener('click',()=>{if(confirm('Permanently erase all records in this temporary demo?'))void action(async()=>{await request('reset',{});clearDrafts();await refresh();});});
void action(refresh);
`;
